### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by SirGamers** [chowloader/chowloader#2]
1. this hasn't been updated in a while, are you still working on this or no?
2. could you possibly explain how this works (im interested in how it works, like how do you read the chowjs files and such)

**Comment by pharuxtan** [comment]
Hey, sorry for the late response, actually i still want to work on it. But at the side i do my study, and it is taking me time. So i actually don't have much time to dedicate to this project. The actual state of the project is converting the QuickJS bytecode to disassembled JavaScript. It is a long and crucial step to understand deeply the javascript RPG Maker MV plugins, and the difference from the NW.js Steam version for modders. After this step of converting the QuickJS bytecode is done. The project will go to stable and usable state faster.

If you have any further question on internal stuff you're asking at your second point, don't mind ask me on discord, my tag is pharuxtan, it'll be easier that way! 🙂

**Comment by SirGamers** [comment]
Cool!
Very good work you’re doing here
Also I get it, studies first, side projects later
(If I ever do message you my discord is cflury)
